knp_paginator :
    page_range : 5                        # nombre de liens affichés dans le menu de pagination (ex : vous avez 10 pages, une page_range de 3, sur la 5ème page vous verrez des liens vers les pages 4, 5, 6) 
    default_options :
        page_name : page                  # nom du paramètre de requête de la page 
        sort_field_name : sort            # nom du paramètre de requête du champ de tri 
        sort_direction_name : direction   # nom du paramètre de requête du sens de tri 
        distinct : true                   #garantir des résultats distincts, utile lorsque les requêtes ORM utilisent des instructions GROUP BY 
        filter_field_name : filterField   # nom du paramètre de requête du champ de filtre 
        filter_value_name : filterValue   # valeur du filtre nom du paramètre de requête 
    template :
        pagination: "partials/_pagination.html.twig"
        # pagination : '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'      # pagination coulissante contrôles template 
        # sortable : '@KnpPaginator/Pagination/sortable_link.html.twig'  # filtrer le modèle de lien de 
        # filtration : '@KnpPaginator/Pagination/filtration.html.twig'   # modèle de filtres